### PR TITLE
feature(database): added docker seeds

### PR DESCRIPTION
**Pull request by RedJanvier**
- ✔ Modified users table for userid field to be self incrementing
- ✔ Added users seeds to the docker image in users table

### CODE REVIEW

**Comment by RedJanvier** [comment]
[Create Database Designs](https://trello.com/c/RzTVQYTu/9-create-database-designs)

**Comment by RedJanvier** [comment]
[Create Database Designs](https://trello.com/c/RzTVQYTu/9-create-database-designs)

**Review by TumoM — APPROVED** [review]
Seed setup look good for Users table.

**Comment by RedJanvier** [comment]
> 
> @TumoM
> Seed setup look good for Users table.

Was it an error to change the UserId column to be serial?

**Comment by TumoM** [comment]
@RedJanvier 
I do not think it was. Serial should just make sure that the value is auto generated and incremented, even though we do not inset an id when inserting new users. So seems good to me :)

**Comment by RedJanvier** [comment]
@TumoM 
Thanks for the approval

**Review by yashShelatkar — APPROVED** [review]
Looks Good

**Pull request merged**
